# Generated by Django 5.1.2 on 2024-12-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Meetup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("place", models.CharField(max_length=255)),
                ("place_description", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default=None,
                        null=True,
                        upload_to="meetup_images",
                        verbose_name="이미지",
                    ),
                ),
                ("started_at", models.DateTimeField(default=None, null=True)),
                ("ended_at", models.DateTimeField(default=None, null=True)),
                ("ad_title", models.CharField(max_length=255)),
                ("ad_ended_at", models.DateTimeField()),
                ("is_public", models.BooleanField(default=True)),
                (
                    "category",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
