# Generated by Django 5.1.2 on 2024-11-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetup", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="meetup",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="이미지"
            ),
        ),
    ]
