# Generated by Django 5.1.2 on 2024-12-24 07:16

import django.db.models.deletion
import meetup.models.proposal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetup", "0003_member"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Proposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("text", models.CharField(blank=True, default="", verbose_name="내용")),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PENDING", "대기"),
                            ("ACCEPTANCE", "수락"),
                            ("REFUSE", "거절"),
                            ("IGNORE", "무시"),
                        ],
                        default=meetup.models.proposal.Proposal.ProposalStatus[
                            "PENDING"
                        ],
                        verbose_name="상태",
                    ),
                ),
                (
                    "meetup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="meetup.meetup",
                        verbose_name="모임",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="회원",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
