# Generated by Django 5.1.2 on 2024-12-24 08:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetup", "0004_proposal"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[("organizer", "모임장"), ("member", "모임원")],
                default="member",
                verbose_name="역할",
            ),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "대기"),
                    ("acceptance", "수락"),
                    ("refuse", "거절"),
                    ("ignore", "무시"),
                ],
                default="pending",
                verbose_name="상태",
            ),
        ),
        migrations.AddConstraint(
            model_name="member",
            constraint=models.UniqueConstraint(
                fields=("user", "meetup"), name="unique_member_user_meetup"
            ),
        ),
        migrations.AddConstraint(
            model_name="proposal",
            constraint=models.UniqueConstraint(
                fields=("user", "meetup"), name="unique_proposal_user_meetup"
            ),
        ),
    ]
