# Generated by Django 5.1.2 on 2024-12-24 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetup", "0005_alter_member_role_alter_proposal_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("scheduled_at", models.DateTimeField(verbose_name="예정일")),
                ("place", models.CharField(max_length=50, verbose_name="장소")),
                ("address", models.CharField(max_length=50, verbose_name="주소")),
                ("latitude", models.CharField(max_length=50, verbose_name="위도")),
                ("longitude", models.CharField(max_length=50, verbose_name="경도")),
                ("memo", models.CharField(max_length=50, verbose_name="메모")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default=None,
                        null=True,
                        upload_to="schedule_images",
                        verbose_name="이미지",
                    ),
                ),
                (
                    "meetup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="meetup.meetup",
                        verbose_name="모임",
                    ),
                ),
                (
                    "participant",
                    models.ManyToManyField(
                        to=settings.AUTH_USER_MODEL, verbose_name="참여자"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
