# -*- coding: utf-8 -*-
# Generated by Django 5.1.2 on 2024-12-31 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meetup", "0007_meetup_like_count_meetuplike"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MeetupComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("root", models.BigIntegerField(blank=True, default=None, null=True)),
                (
                    "recipient",
                    models.CharField(blank=True, default=None, max_length=16, null=True),
                ),
                ("text", models.TextField()),
                ("is_delete", models.BooleanField(default=True)),
                (
                    "meetup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="meetup.meetup",
                        verbose_name="모임",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="작성자",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ScheduleComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("root", models.BigIntegerField(blank=True, default=None, null=True)),
                (
                    "recipient",
                    models.CharField(blank=True, default=None, max_length=16, null=True),
                ),
                ("text", models.TextField()),
                ("is_delete", models.BooleanField(default=True)),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="meetup.schedule",
                        verbose_name="스케줄",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="작성자",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
