# -*- coding: utf-8 -*-
# Generated by Django 5.1.2 on 2025-01-08 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meetup", "0008_meetupcomment_schedulecomment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meetupcomment",
            name="is_delete",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="schedulecomment",
            name="is_delete",
            field=models.BooleanField(default=False),
        ),
    ]
