# -*- coding: utf-8 -*-
# Generated by Django 5.1.2 on 2025-01-08 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meetup", "0009_alter_meetupcomment_is_delete_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meetup",
            name="ad_ended_at",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="meetup",
            name="ended_at",
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="meetup",
            name="started_at",
            field=models.DateField(default=None, null=True),
        ),
    ]
