# -*- coding: utf-8 -*-
# Generated by Django 5.1.2 on 2025-05-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meetup", "0010_alter_meetup_ad_ended_at_alter_meetup_ended_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposal",
            name="is_hide_to_proposer",
            field=models.BooleanField(default=False, verbose_name="신청자 숨김 여부"),
        ),
        migrations.AlterField(
            model_name="meetup",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="meetup",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="meetupcomment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="meetupcomment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="meetuplike",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="meetuplike",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="member",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="member",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="schedulecomment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="schedulecomment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
