# -*- coding: utf-8 -*-
# Generated by Django 5.2.2 on 2025-06-14 02:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "meetup",
            "0011_proposal_is_hide_to_proposer_alter_meetup_created_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="meetup",
            name="image",
            field=models.CharField(blank=True, default="", null=True, verbose_name="이미지"),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="image",
            field=models.CharField(blank=True, default="", null=True, verbose_name="이미지"),
        ),
    ]
