# -*- coding: utf-8 -*-
# Generated by Django 5.2.2 on 2025-06-14 02:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_alter_user_created_at_alter_user_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.CharField(blank=True, default="", null=True, verbose_name="프로필 이미지"),
        ),
    ]
